### ISSUE TITLE
在某些机型上扫码不成功

### ISSUE THREAD

**Issue by Dawnton** [0xZhangKe/QRCodeView#4]
你好 我用这个在只能POS机上做测试，相机成功打开了，但是一直识别失败，下面是打开扫码页面后的log

08-16 16:25:16.654 22810-22810/com.achpay.wallet I/SurfaceView: surfaceCreated callback +, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:16.721 22810-22810/com.achpay.wallet D/Camera-JNI: (tid:22810)[MtkJNICameraContext] this:0xb8c14c60 camera->getStrongCount(3) 
08-16 16:25:16.725 22810-22810/com.achpay.wallet I/CameraFramework: Camera framework getParameters =3dnr-mode=off;3dnr-mode-values=off;afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=fixed;focus-mode-values=fixed;gesture-shot=false;gesture-shot-supported=true;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=2;max-zoom=10;mfb=off;mfb-values=off;min-exposure-compensation=-3;mtk-123-shad-s=false;mtk-awb-s=false;mtk-cam-mode=0;mtk-shad-s=false;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=2560x1920;picture-size-values=320x240,640x480,1024x768,1280x960,1600x1200,480x320,960x640,1440x960,800x480,1280x720,1280x768,1920x1088,1600x960;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,24,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,960x640,1280x720,1440x960,1440x1080,1600x960,1600x1200,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=254;smooth-zoom-supported=true;sr-awb-s=false;sr-shad-s=false;stereo-distance-measurement=off;stereo-distance-measurement-values=off;stereo-image-refocus=off;stereo-image-refocus-values=off;sv1-s=1;sv2-s=1;vertical-view-angle=49;vfb-supported=false;vfb-supported-values=false;video-frame-format=android-opaque;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,480x320,640x480,720x480,864x480,1280x720,1920x1080,1920x1088;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;vr-buf-count=10;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
08-16 16:25:16.729 22810-22810/com.achpay.wallet I/CameraConfiguration: Supported preview sizes: 176x144 320x240 352x288 480x320 480x368 640x480 720x480 800x480 800x600 864x480 960x540 960x640 1280x720 1440x960 1440x1080 1600x960 1600x1200 1920x1088 
    Using largest suitable preview size: Point(1920, 1088)
08-16 16:25:16.729 22810-22810/com.achpay.wallet V/CameraFramework: set Key = preview-size, value = 1920x1088
    set Key = picture-size, value = 320x240
08-16 16:25:16.730 22810-22810/com.achpay.wallet I/CameraConfiguration: Supported picture sizes: 320x240 640x480 1024x768 1280x960 1600x1200 480x320 960x640 1440x960 800x480 1280x720 1280x768 1920x1088 1600x960 
    Using largest suitable picture size: Point(1920, 1088)
08-16 16:25:16.730 22810-22810/com.achpay.wallet V/CameraFramework: set Key = picture-size, value = 1920x1088
08-16 16:25:16.732 22810-22810/com.achpay.wallet V/CameraFramework: set Key = focus-mode, value = continuous-picture
    set Key = scene-mode, value = auto
08-16 16:25:16.737 22810-22810/com.achpay.wallet W/System.err: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:3076)
        at com.zhangke.qrcodeview.QRCodeView.openCamera(QRCodeView.java:180)
        at com.zhangke.qrcodeview.QRCodeView.surfaceCreated(QRCodeView.java:138)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:675)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2348)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
08-16 16:25:16.738 22810-22810/com.achpay.wallet W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-16 16:25:16.740 22810-22810/com.achpay.wallet I/CameraFramework: Camera framework getParameters =3dnr-mode=off;3dnr-mode-values=off;afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=fixed;focus-mode-values=fixed;gesture-shot=false;gesture-shot-supported=true;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=2;max-zoom=10;mfb=off;mfb-values=off;min-exposure-compensation=-3;mtk-123-shad-s=false;mtk-awb-s=false;mtk-cam-mode=0;mtk-shad-s=false;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=2560x1920;picture-size-values=320x240,640x480,1024x768,1280x960,1600x1200,480x320,960x640,1440x960,800x480,1280x720,1280x768,1920x1088,1600x960;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,24,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,960x640,1280x720,1440x960,1440x1080,1600x960,1600x1200,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=254;smooth-zoom-supported=true;sr-awb-s=false;sr-shad-s=false;stereo-distance-measurement=off;stereo-distance-measurement-values=off;stereo-image-refocus=off;stereo-image-refocus-values=off;sv1-s=1;sv2-s=1;vertical-view-angle=49;vfb-supported=false;vfb-supported-values=false;video-frame-format=android-opaque;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,480x320,640x480,720x480,864x480,1280x720,1920x1080,1920x1088;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;vr-buf-count=10;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
08-16 16:25:16.747 22810-22810/com.achpay.wallet I/CameraFramework: Camera framework getParameters =3dnr-mode=off;3dnr-mode-values=off;afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=fixed;focus-mode-values=fixed;gesture-shot=false;gesture-shot-supported=true;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=2;max-zoom=10;mfb=off;mfb-values=off;min-exposure-compensation=-3;mtk-123-shad-s=false;mtk-awb-s=false;mtk-cam-mode=0;mtk-shad-s=false;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=2560x1920;picture-size-values=320x240,640x480,1024x768,1280x960,1600x1200,480x320,960x640,1440x960,800x480,1280x720,1280x768,1920x1088,1600x960;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,24,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,960x640,1280x720,1440x960,1440x1080,1600x960,1600x1200,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=254;smooth-zoom-supported=true;sr-awb-s=false;sr-shad-s=false;stereo-distance-measurement=off;stereo-distance-measurement-values=off;stereo-image-refocus=off;stereo-image-refocus-values=off;sv1-s=1;sv2-s=1;vertical-view-angle=49;vfb-supported=false;vfb-supported-values=false;video-frame-format=android-opaque;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,480x320,640x480,720x480,864x480,1280x720,1920x1080,1920x1088;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;vr-buf-count=10;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
08-16 16:25:16.753 22810-22810/com.achpay.wallet I/CameraFramework: Camera framework getParameters =3dnr-mode=off;3dnr-mode-values=off;afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mono,negative,sepia,aqua,whiteboard,blackboard;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-step-max=0;flash-step-min=0;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=fixed;focus-mode-values=fixed;gesture-shot=false;gesture-shot-supported=true;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,256x192;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=9;max-num-ot=2;max-zoom=10;mfb=off;mfb-values=off;min-exposure-compensation=-3;mtk-123-shad-s=false;mtk-awb-s=false;mtk-cam-mode=0;mtk-shad-s=false;native-pip=false;native-pip-supported=false;picture-format=jpeg;picture-format-values=jpeg;picture-size=2560x1920;picture-size-values=320x240,640x480,1024x768,1280x960,1600x1200,480x320,960x640,1440x960,800x480,1280x720,1280x768,1920x1088,1600x960;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,24,30;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,960x640,1280x720,1440x960,1440x1080,1600x960,1600x1200,1920x1088;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr;sen-mode-s=0;sensor-type=254;smooth-zoom-supported=true;sr-awb-s=false;sr-shad-s=false;stereo-distance-measurement=off;stereo-distance-measurement-values=off;stereo-image-refocus=off;stereo-image-refocus-values=off;sv1-s=1;sv2-s=1;vertical-view-angle=49;vfb-supported=false;vfb-supported-values=false;video-frame-format=android-opaque;video-hdr=off;video-hdr-values=off;video-size=640x480;video-size-values=176x144,320x240,352x288,480x320,640x480,720x480,864x480,1280x720,1920x1080,1920x1088;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;vr-buf-count=10;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
08-16 16:25:16.756 22810-22810/com.achpay.wallet E/QRCodeView: surfaceCreated
08-16 16:25:17.164 22810-22810/com.achpay.wallet I/SurfaceView: surfaceCreated callback -, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    surfaceChanged -- format=4 w=540 h=850, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    surfaceChanged callback +, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    surfaceChanged callback -, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    surfaceRedrawNeeded, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    finishedDrawing, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.169 22810-22810/com.achpay.wallet V/SurfaceView: Layout: x=0 y=38 w=540 h=850, frame=Rect(0, 0 - 540, 850), this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.170 22810-22810/com.achpay.wallet I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
08-16 16:25:17.178 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    Cur surface: Surface(name=null)/@0x270360f3, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.185 22810-22810/com.achpay.wallet I/SurfaceView: New surface: Surface(name=null)/@0x12ec81b0, vis=true, frame=Rect(0, 38 - 540, 888), this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
    surfaceRedrawNeeded, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.186 22810-22810/com.achpay.wallet I/SurfaceView: finishedDrawing, this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.187 22810-22810/com.achpay.wallet V/SurfaceView: Layout: x=0 y=38 w=540 h=850, frame=Rect(0, 0 - 540, 850), this = android.view.SurfaceView{f8f73d6 V.E..... ......ID 0,0-540,850}
08-16 16:25:17.190 22810-22810/com.achpay.wallet I/SurfaceView: Punch a hole(dispatchDraw), w = 540, h = 850, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:17.197 22810-22810/com.achpay.wallet V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#1810100
    START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{3929f880 V.E..... R.....I. 0,0-540,888} ic=null tba=android.view.inputmethod.EditorInfo@e4127ae controlFlags=#104
08-16 16:25:17.210 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {a69194f}
08-16 16:25:17.211 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- setFrame, this = android.view.SurfaceView{f8f73d6 V.E..... ......I. 0,0-540,850}
    updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ......I. 0,0-540,850}
08-16 16:25:17.212 22810-22810/com.achpay.wallet I/SurfaceView: Punch a hole(dispatchDraw), w = 540, h = 850, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:17.213 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:17.214 22810-22858/com.achpay.wallet D/GraphicBuffer: register, handle(0xb8c63750) (w:540 h:888 s:544 f:0x1 u:0x000f02)
08-16 16:25:17.245 22810-22858/com.achpay.wallet D/MALI: _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000001, state 0xb88feb60
    _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb8888b78
    _egl_make_current:906: [MALI] Map __ctx 0x40000001 to ctx 0xb8904758
08-16 16:25:17.245 22810-22858/com.achpay.wallet D/OpenGLRenderer: Flushing caches (mode 0)
08-16 16:25:17.246 22810-22858/com.achpay.wallet D/Surface: Surface::disconnect(this=0xb8b737c0,api=1)
08-16 16:25:17.246 22810-22858/com.achpay.wallet D/GraphicBuffer: unregister, handle(0xb8ccdf78) (w:540 h:888 s:544 f:0x1 u:0x000f02)
    unregister, handle(0xb8a54ff8) (w:540 h:888 s:544 f:0x1 u:0x000f02)
08-16 16:25:17.247 22810-22858/com.achpay.wallet D/GraphicBuffer: unregister, handle(0xb88cc160) (w:540 h:888 s:544 f:0x1 u:0x000f02)
    unregister, handle(0xb8a496e0) (w:540 h:888 s:544 f:0x1 u:0x000f02)
08-16 16:25:17.249 22810-22858/com.achpay.wallet D/OpenGLRenderer: Flushing caches (mode 0)
08-16 16:25:17.465 22810-22810/com.achpay.wallet E/QRCodeView: restartPreviewAndDecode: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhangke.qrcodeview.PreviewCallback.setHandler(android.os.Handler, int)' on a null object reference
        at com.zhangke.qrcodeview.QRCodeView.restartPreviewAndDecode(QRCodeView.java:241)
        at com.zhangke.qrcodeview.QRCodeView.access$200(QRCodeView.java:30)
        at com.zhangke.qrcodeview.QRCodeView$1$1.run(QRCodeView.java:213)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-16 16:25:17.599 22810-22858/com.achpay.wallet D/OpenGLRenderer: Flushing caches (mode 0)
    Flushing caches (mode 0)
08-16 16:25:17.611 22810-22810/com.achpay.wallet D/ActivityThread: ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@260af29e
08-16 16:25:18.345 22810-23520/com.achpay.wallet I/ACHPAY_WALLET: MessageService ==  : onMessage---{"returnCode":"0000","returnMsg":"SUCCESS","data":{"blockNum":0,"blockTxId":"","confirmBlockNums":0,"cryptocurrency":"BTC","cryptocurrencyId":1,"currency":"CNY","currencyId":1,"diffQuantity":"0.00000000","merchantId":"efd94acb167d45f6b218d552fafb1467","networkFee":"0.00000000","orderDiffQuantityFait":"0.00","orderId":"2018081616250396597","orderQuantityFait":"25.00","orderReceiveQuantityFait":"25.00","plateformFee":"0.00000000","quantity":"0.00056239","quantityFait":"25.00","receiveFait":"0.00","receiveQuantity":"0.00000000","receiveTime":"2018-08-16 16:25:04","result":"DEALING","resultMsg":"已接收","sign":"4e6d49324e6d51785a6d4e69595451774d5455304e7a646959544d784e444e6c4d5463355a5455325a57513d","sysFlowNo":"gw2018081608250400001"}}
08-16 16:25:18.706 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.707 22810-22858/com.achpay.wallet D/MALI: _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000001, state 0xb88feb60
    _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb8888b78
    _egl_make_current:906: [MALI] Map __ctx 0x40000001 to ctx 0xb8904758
08-16 16:25:18.707 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:18.708 22810-22858/com.achpay.wallet D/GraphicBuffer: register, handle(0xb8a496e0) (w:540 h:888 s:544 f:0x1 u:0x000f02)
08-16 16:25:18.723 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.724 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:18.726 22810-22858/com.achpay.wallet D/GraphicBuffer: register, handle(0xb88b7030) (w:540 h:888 s:544 f:0x1 u:0x000f02)
08-16 16:25:18.740 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.742 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:18.757 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.758 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:18.773 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.775 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)
08-16 16:25:18.790 22810-22810/com.achpay.wallet I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{f8f73d6 V.E..... ........ 0,0-540,850}
08-16 16:25:18.792 22810-22858/com.achpay.wallet D/Surface: Surface::setBuffersDimensions(this=0xb8bf33a8,w=540,h=888)

**Comment by 0xZhangKe** [comment]
错误信息太多了最好把关键信息发出来。
